### ISSUE TITLE
List Bounties

### ISSUE THREAD

**Issue by shekohex** [sunshine-protocol/sunshine-bounty#137]
How do I list (browse) all available bounties?

Currently, there is no API for the UI/CLI to browse the bounties.

**Comment by 4meta5** [comment]
Funny, I thought this would be easier than I'm finding it now, related https://github.com/paritytech/substrate-subxt/issues/144

@dvc94ch any suggestions here? Could I define a public method like

```rust
impl<T: Trait> Module<T> {
    pub fn open_bounties() -> Option<Vec<T::BountyId>> {
        let ret = <Bounties<T>::iter().filter(|(_, b)| b.is_some()).map(|(id, _)| id).collect::<Vec<T::BountyId>>();
        if ret.is_empty() { None } else { Some(ret) }
    }  
}
```

Can I call this method with `substrate-subxt`? It's not a `Call` because I don't need the signer, but it's also not a `Store`.

**Comment by dvc94ch** [comment]
Not sure: https://github.com/paritytech/substrate-subxt/issues/144

Will have to look into it
